### ISSUE TITLE
Add time picking UI for market expiry during market creation

### ISSUE THREAD

**Issue by thinkloop** [AugurProject/augur-ui-react-components#27]
Add UI to allow users to pick a time (in addition to date) during market creation process. See if the existing widget allows this and that it is nice, or consider another widget for the time:

![image](https://cloud.githubusercontent.com/assets/118814/16138016/240b362c-3407-11e6-92c6-1bacb6d2b5d8.png)

**Comment by JohnDanz** [comment]
I've done some research and it turns out that the date picker we use, "react-date-picker" is 1 major version behind the current release. If we wanted to add time, we would need to update the version, so i did. Then after reading through the docs, I've found that in order to add time we will need to change the datePicker from a calendar view to an input box that when clicked/moused over presents a calendar view with a clock. This will allow us to successfully grab time. 

A question I have is how granular do we want to get with the time? Down to the second, or is minute ok?

**Comment by tinybike** [comment]
Down to the second!

**Comment by thinkloop** [comment]
no nanos?

**Comment by JohnDanz** [comment]
oh and Date Format? MM/DD/YYYY? YYYY/MM/DD? etc?

**Comment by thinkloop** [comment]
if we hide the box, no need to display until later when it will be provided formatted by the augur repo

**Comment by tinybike** [comment]
Added in 6e944c94a9adfa2a5e1808cad0a9cbe1d390c3c2.
